//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountdropdown_group2
    {
        public accountdropdown_group2()
        {
            this.addaccount_group2 = new HashSet<addaccount_group2>();
        }
    
        public int id { get; set; }
        public string Accounttype { get; set; }
    
        public virtual ICollection<addaccount_group2> addaccount_group2 { get; set; }
    }
}
