//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addaccount_group2
    {
        public addaccount_group2()
        {
            this.transactiontable_group2 = new HashSet<transactiontable_group2>();
        }
    
        public long AccountId { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public string AccountStatus { get; set; }
    
        public virtual accountdropdown_group2 accountdropdown_group2 { get; set; }
        public virtual CustomerTable_group2 CustomerTable_group2 { get; set; }
        public virtual ICollection<transactiontable_group2> transactiontable_group2 { get; set; }
    }
}
