//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bankEntities : DbContext
    {
        public bankEntities()
            : base("name=bankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city_group2> city_group2 { get; set; }
        public virtual DbSet<CustomerTable_group2> CustomerTable_group2 { get; set; }
        public virtual DbSet<loginexecutive_group2> loginexecutive_group2 { get; set; }
        public virtual DbSet<state_group2> state_group2 { get; set; }
        public virtual DbSet<accountdropdown_group2> accountdropdown_group2 { get; set; }
        public virtual DbSet<addaccount_group2> addaccount_group2 { get; set; }
        public virtual DbSet<transactiontable_group2> transactiontable_group2 { get; set; }
    
        public virtual int sp_CustomerTable_group2(Nullable<long> customerID, Nullable<long> aadhaarID, string customerName, Nullable<System.DateTime> dob, string addressLine1, string addressLine2, Nullable<int> state, Nullable<int> city, Nullable<long> contact, string email, ObjectParameter customeridout)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            var aadhaarIDParameter = aadhaarID.HasValue ?
                new ObjectParameter("AadhaarID", aadhaarID) :
                new ObjectParameter("AadhaarID", typeof(long));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("Dob", dob) :
                new ObjectParameter("Dob", typeof(System.DateTime));
    
            var addressLine1Parameter = addressLine1 != null ?
                new ObjectParameter("AddressLine1", addressLine1) :
                new ObjectParameter("AddressLine1", typeof(string));
    
            var addressLine2Parameter = addressLine2 != null ?
                new ObjectParameter("AddressLine2", addressLine2) :
                new ObjectParameter("AddressLine2", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(int));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var contactParameter = contact.HasValue ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(long));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CustomerTable_group2", customerIDParameter, aadhaarIDParameter, customerNameParameter, dobParameter, addressLine1Parameter, addressLine2Parameter, stateParameter, cityParameter, contactParameter, emailParameter, customeridout);
        }
    
        public virtual ObjectResult<sp_loginexecutive_group2_Result> sp_loginexecutive_group2(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loginexecutive_group2_Result>("sp_loginexecutive_group2", usernameParameter);
        }
    
        public virtual ObjectResult<sp_state_group2_Result> sp_state_group2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_group2_Result>("sp_state_group2");
        }
    
        public virtual ObjectResult<sp_view_CustomerTable_group2_Result> sp_view_CustomerTable_group2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_CustomerTable_group2_Result>("sp_view_CustomerTable_group2");
        }
    
        public virtual ObjectResult<sp_viewbyid_CustomerTable_group2_Result> sp_viewbyid_CustomerTable_group2(Nullable<long> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewbyid_CustomerTable_group2_Result>("sp_viewbyid_CustomerTable_group2", customerIDParameter);
        }
    
        public virtual int sp_deletecustomer_group2(Nullable<long> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletecustomer_group2", customerIDParameter);
        }
    
        public virtual int sp_deletebyid_CustomerTable_group2(Nullable<long> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletebyid_CustomerTable_group2", customerIDParameter);
        }
    
        public virtual int sp_addaccount_group2(Nullable<long> accountId, Nullable<long> customerID, Nullable<int> accountType, Nullable<decimal> depositAmount, ObjectParameter accountidout)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            var accountTypeParameter = accountType.HasValue ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(int));
    
            var depositAmountParameter = depositAmount.HasValue ?
                new ObjectParameter("DepositAmount", depositAmount) :
                new ObjectParameter("DepositAmount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addaccount_group2", accountIdParameter, customerIDParameter, accountTypeParameter, depositAmountParameter, accountidout);
        }
    
        public virtual ObjectResult<sp_view_addaccount_group2_Result> sp_view_addaccount_group2(Nullable<long> customerid)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_addaccount_group2_Result>("sp_view_addaccount_group2", customeridParameter);
        }
    
        public virtual ObjectResult<sp_viewAccount_group2_Result> sp_viewAccount_group2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewAccount_group2_Result>("sp_viewAccount_group2");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_accountTypecheck_gropu2(Nullable<long> customerid)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_accountTypecheck_gropu2", customeridParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_checkAccount_group2(Nullable<long> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("customerID", customerID) :
                new ObjectParameter("customerID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_checkAccount_group2", customerIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_checknoofAccounts_group2(Nullable<long> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_checknoofAccounts_group2", customerIDParameter);
        }
    
        public virtual ObjectResult<sp_viewCashier_group2_Result> sp_viewCashier_group2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewCashier_group2_Result>("sp_viewCashier_group2");
        }
    
        public virtual ObjectResult<cashierViewAccountbyId_group2_Result> cashierViewAccountbyId_group2(Nullable<long> acc_id)
        {
            var acc_idParameter = acc_id.HasValue ?
                new ObjectParameter("acc_id", acc_id) :
                new ObjectParameter("acc_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cashierViewAccountbyId_group2_Result>("cashierViewAccountbyId_group2", acc_idParameter);
        }
    
        public virtual int DepositAmount_group2(Nullable<long> accountId, string accountType, string transactionType, Nullable<decimal> amount, Nullable<decimal> beforebalance, ObjectParameter latestbalance)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var accountTypeParameter = accountType != null ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(string));
    
            var transactionTypeParameter = transactionType != null ?
                new ObjectParameter("TransactionType", transactionType) :
                new ObjectParameter("TransactionType", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var beforebalanceParameter = beforebalance.HasValue ?
                new ObjectParameter("beforebalance", beforebalance) :
                new ObjectParameter("beforebalance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DepositAmount_group2", accountIdParameter, accountTypeParameter, transactionTypeParameter, amountParameter, beforebalanceParameter, latestbalance);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Totaltransactions(Nullable<long> customerId, Nullable<System.DateTime> date)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Totaltransactions", customerIdParameter, dateParameter);
        }
    
        public virtual int sp_WithdrawAmount_group2(Nullable<long> accountId, string accountType, string transactionType, Nullable<decimal> amount, Nullable<decimal> beforebalance, ObjectParameter latestbalance)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var accountTypeParameter = accountType != null ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(string));
    
            var transactionTypeParameter = transactionType != null ?
                new ObjectParameter("TransactionType", transactionType) :
                new ObjectParameter("TransactionType", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var beforebalanceParameter = beforebalance.HasValue ?
                new ObjectParameter("beforebalance", beforebalance) :
                new ObjectParameter("beforebalance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_WithdrawAmount_group2", accountIdParameter, accountTypeParameter, transactionTypeParameter, amountParameter, beforebalanceParameter, latestbalance);
        }
    
        public virtual int sp_Deposit_group2(Nullable<long> accountId, string accountType, string transactionType, Nullable<decimal> amount, Nullable<decimal> beforebalance, ObjectParameter latestbalance)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var accountTypeParameter = accountType != null ?
                new ObjectParameter("AccountType", accountType) :
                new ObjectParameter("AccountType", typeof(string));
    
            var transactionTypeParameter = transactionType != null ?
                new ObjectParameter("TransactionType", transactionType) :
                new ObjectParameter("TransactionType", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var beforebalanceParameter = beforebalance.HasValue ?
                new ObjectParameter("beforebalance", beforebalance) :
                new ObjectParameter("beforebalance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Deposit_group2", accountIdParameter, accountTypeParameter, transactionTypeParameter, amountParameter, beforebalanceParameter, latestbalance);
        }
    
        public virtual int sp_deleteAccount_group2(Nullable<long> accountId, Nullable<long> customerID, Nullable<decimal> depositAmount)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            var depositAmountParameter = depositAmount.HasValue ?
                new ObjectParameter("DepositAmount", depositAmount) :
                new ObjectParameter("DepositAmount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deleteAccount_group2", accountIdParameter, customerIDParameter, depositAmountParameter);
        }
    
        public virtual ObjectResult<sp_viewbyAccountID_group2_Result> sp_viewbyAccountID_group2(Nullable<long> accountid)
        {
            var accountidParameter = accountid.HasValue ?
                new ObjectParameter("accountid", accountid) :
                new ObjectParameter("accountid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewbyAccountID_group2_Result>("sp_viewbyAccountID_group2", accountidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_forchecknoofaccountbycusId(Nullable<long> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_forchecknoofaccountbycusId", customerIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_forcheckwhichaccounttype(Nullable<long> accountId)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_forcheckwhichaccounttype", accountIdParameter);
        }
    
        public virtual int sp_transfer_group2(Nullable<long> acc_idS, Nullable<long> acc_idD, Nullable<int> acc_typeS, Nullable<int> acc_typeD, Nullable<decimal> pre_balS, Nullable<decimal> pre_balD, Nullable<decimal> amount, ObjectParameter up_balS, ObjectParameter up_balD)
        {
            var acc_idSParameter = acc_idS.HasValue ?
                new ObjectParameter("acc_idS", acc_idS) :
                new ObjectParameter("acc_idS", typeof(long));
    
            var acc_idDParameter = acc_idD.HasValue ?
                new ObjectParameter("acc_idD", acc_idD) :
                new ObjectParameter("acc_idD", typeof(long));
    
            var acc_typeSParameter = acc_typeS.HasValue ?
                new ObjectParameter("acc_typeS", acc_typeS) :
                new ObjectParameter("acc_typeS", typeof(int));
    
            var acc_typeDParameter = acc_typeD.HasValue ?
                new ObjectParameter("acc_typeD", acc_typeD) :
                new ObjectParameter("acc_typeD", typeof(int));
    
            var pre_balSParameter = pre_balS.HasValue ?
                new ObjectParameter("pre_balS", pre_balS) :
                new ObjectParameter("pre_balS", typeof(decimal));
    
            var pre_balDParameter = pre_balD.HasValue ?
                new ObjectParameter("pre_balD", pre_balD) :
                new ObjectParameter("pre_balD", typeof(decimal));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_transfer_group2", acc_idSParameter, acc_idDParameter, acc_typeSParameter, acc_typeDParameter, pre_balSParameter, pre_balDParameter, amountParameter, up_balS, up_balD);
        }
    
        public virtual ObjectResult<sp_selectCustomerAccountIdforTransfer_group2_Result> sp_selectCustomerAccountIdforTransfer_group2(Nullable<long> cus_id, Nullable<long> acc_id)
        {
            var cus_idParameter = cus_id.HasValue ?
                new ObjectParameter("cus_id", cus_id) :
                new ObjectParameter("cus_id", typeof(long));
    
            var acc_idParameter = acc_id.HasValue ?
                new ObjectParameter("acc_id", acc_id) :
                new ObjectParameter("acc_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectCustomerAccountIdforTransfer_group2_Result>("sp_selectCustomerAccountIdforTransfer_group2", cus_idParameter, acc_idParameter);
        }
    
        public virtual ObjectResult<sp_city_group2_Result> sp_city_group2(Nullable<int> stateid)
        {
            var stateidParameter = stateid.HasValue ?
                new ObjectParameter("stateid", stateid) :
                new ObjectParameter("stateid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_city_group2_Result>("sp_city_group2", stateidParameter);
        }
    
        public virtual ObjectResult<sp_printstatement_group2_Result> sp_printstatement_group2(Nullable<long> accountid, Nullable<int> nooftransactions)
        {
            var accountidParameter = accountid.HasValue ?
                new ObjectParameter("accountid", accountid) :
                new ObjectParameter("accountid", typeof(long));
    
            var nooftransactionsParameter = nooftransactions.HasValue ?
                new ObjectParameter("nooftransactions", nooftransactions) :
                new ObjectParameter("nooftransactions", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_printstatement_group2_Result>("sp_printstatement_group2", accountidParameter, nooftransactionsParameter);
        }
    
        public virtual ObjectResult<sp_statementbyDate_group2_Result> sp_statementbyDate_group2(Nullable<long> accountId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("AccountId", accountId) :
                new ObjectParameter("AccountId", typeof(long));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_statementbyDate_group2_Result>("sp_statementbyDate_group2", accountIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<sp_view_CustomerTable_CONCAT_GROUP2_Result1> sp_view_CustomerTable_CONCAT_GROUP2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_CustomerTable_CONCAT_GROUP2_Result1>("sp_view_CustomerTable_CONCAT_GROUP2");
        }
    
        public virtual ObjectResult<sp_viewaccounttablewithstatus_Result> sp_viewaccounttablewithstatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewaccounttablewithstatus_Result>("sp_viewaccounttablewithstatus");
        }
    
        //public virtual ObjectResult<viewaccountnameinlist_Result> viewaccountnameinlist()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewaccountnameinlist_Result>("viewaccountnameinlist");
        //}
    
        //public virtual ObjectResult<sp_viewaccountnameinlist_Result> sp_viewaccountnameinlist()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewaccountnameinlist_Result>("sp_viewaccountnameinlist");
        //}
    }
}
