//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable_group2
    {
        public CustomerTable_group2()
        {
            this.addaccount_group2 = new HashSet<addaccount_group2>();
        }
    
        public long CustomerID { get; set; }
        public long AadhaarID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<long> Contact { get; set; }
        public string Email { get; set; }
        public Nullable<int> NoofAccounts { get; set; }
        public string CustomerStatus { get; set; }
    
        public virtual city_group2 city_group2 { get; set; }
        public virtual state_group2 state_group2 { get; set; }
        public virtual ICollection<addaccount_group2> addaccount_group2 { get; set; }
    }
}
