//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginexecutive_group2
    {
        public int loginid { get; set; }
        public string Username { get; set; }
        public string userpassword { get; set; }
        public Nullable<int> userroleid { get; set; }
    }
}
