//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    
    public partial class sp_view_CustomerTable_CONCAT_GROUP2_Result1
    {
        public long CustomerID { get; set; }
        public long AadhaarID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Address { get; set; }
        public Nullable<long> Contact { get; set; }
        public string Email { get; set; }
        public string CustomerStatus { get; set; }
        public Nullable<int> NoofAccounts { get; set; }
    }
}
