//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_Banking_Group2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_group2
    {
        public state_group2()
        {
            this.city_group2 = new HashSet<city_group2>();
            this.CustomerTable_group2 = new HashSet<CustomerTable_group2>();
        }
    
        public int stateid { get; set; }
        public string statename { get; set; }
    
        public virtual ICollection<city_group2> city_group2 { get; set; }
        public virtual ICollection<CustomerTable_group2> CustomerTable_group2 { get; set; }
    }
}
